name: deploy to cdn

on:
    push:
      branches: main
    pull_request:
      branches: main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      
      - name: upload to s3
        run: |
          aws s3 cp peasy.js s3://peasy-cdn/ --endpoint-url ${{secrets.S3_ENDPOINT}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
      
    
      - name: purge cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_CLIENT_ID}}/purge_cache" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{secrets.CLOUDFLARE_API_TOKEN}}" \
          -d '{"files":[{"url":"https://cdn.peasy.so/peasy.js"}]}'





        